<?php
$data = array (
  0 => 
  array (
    'cat_id' => '683',
    'cat_name' => '家装案例',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '684',
    'cat_name' => '工装案例',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '690',
    'cat_name' => '儿童房',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '687',
    'cat_name' => '餐厅墙',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  4 => 
  array (
    'cat_id' => '688',
    'cat_name' => '卧室墙',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '685',
    'cat_name' => '电视墙',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  6 => 
  array (
    'cat_id' => '689',
    'cat_name' => '端景墙',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '686',
    'cat_name' => '沙发墙',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  8 => 
  array (
    'cat_id' => '696',
    'cat_name' => '休闲娱乐场',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '693',
    'cat_name' => '大型主题场馆',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '694',
    'cat_name' => '综合创意艺术',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '691',
    'cat_name' => '个性艺术涂鸦',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '695',
    'cat_name' => '企事业单位',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '692',
    'cat_name' => '综合教育机构',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>