<?php
$data = array (
  683 => 
  array (
    'cat_id' => '683',
    'cat_name' => '家装案例',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '683',
    'name' => '家装案例',
  ),
  690 => 
  array (
    'cat_id' => '690',
    'cat_name' => '儿童房',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '690',
    'name' => '儿童房',
  ),
  687 => 
  array (
    'cat_id' => '687',
    'cat_name' => '餐厅墙',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '687',
    'name' => '餐厅墙',
  ),
  688 => 
  array (
    'cat_id' => '688',
    'cat_name' => '卧室墙',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '688',
    'name' => '卧室墙',
  ),
  685 => 
  array (
    'cat_id' => '685',
    'cat_name' => '电视墙',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '685',
    'name' => '电视墙',
  ),
  689 => 
  array (
    'cat_id' => '689',
    'cat_name' => '端景墙',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '689',
    'name' => '端景墙',
  ),
  686 => 
  array (
    'cat_id' => '686',
    'cat_name' => '沙发墙',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '686',
    'name' => '沙发墙',
  ),
  684 => 
  array (
    'cat_id' => '684',
    'cat_name' => '工装案例',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '684',
    'name' => '工装案例',
  ),
  696 => 
  array (
    'cat_id' => '696',
    'cat_name' => '休闲娱乐场',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '696',
    'name' => '休闲娱乐场',
  ),
  693 => 
  array (
    'cat_id' => '693',
    'cat_name' => '大型主题场馆',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '693',
    'name' => '大型主题场馆',
  ),
  694 => 
  array (
    'cat_id' => '694',
    'cat_name' => '综合创意艺术',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '694',
    'name' => '综合创意艺术',
  ),
  691 => 
  array (
    'cat_id' => '691',
    'cat_name' => '个性艺术涂鸦',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '691',
    'name' => '个性艺术涂鸦',
  ),
  695 => 
  array (
    'cat_id' => '695',
    'cat_name' => '企事业单位',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '695',
    'name' => '企事业单位',
  ),
  692 => 
  array (
    'cat_id' => '692',
    'cat_name' => '综合教育机构',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '692',
    'name' => '综合教育机构',
  ),
);
?>